/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Validator for the Manual Presence callflow action
    /// </summary>
    [DataContract]
    public partial class CallflowsManualPresence :  IEquatable<CallflowsManualPresence>, IValidatableObject
    {
        /// <summary>
        /// The status to update to
        /// </summary>
        /// <value>The status to update to</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum Idle for value: idle
            /// </summary>
            [EnumMember(Value = "idle")]
            Idle = 1,
            
            /// <summary>
            /// Enum Ringing for value: ringing
            /// </summary>
            [EnumMember(Value = "ringing")]
            Ringing = 2,
            
            /// <summary>
            /// Enum Busy for value: busy
            /// </summary>
            [EnumMember(Value = "busy")]
            Busy = 3
        }

        /// <summary>
        /// The status to update to
        /// </summary>
        /// <value>The status to update to</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CallflowsManualPresence" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CallflowsManualPresence() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CallflowsManualPresence" /> class.
        /// </summary>
        /// <param name="presenceId">The Presence ID to send a presence notification about (required).</param>
        /// <param name="skipModule">When set to true this callflow action is skipped, advancing to the wildcard branch (if any).</param>
        /// <param name="status">The status to update to (default to StatusEnum.Idle).</param>
        public CallflowsManualPresence(string presenceId = default(string), bool? skipModule = default(bool?), StatusEnum? status = StatusEnum.Idle)
        {
            // to ensure "presenceId" is required (not null)
            if (presenceId == null)
            {
                throw new InvalidDataException("presenceId is a required property for CallflowsManualPresence and cannot be null");
            }
            else
            {
                this.PresenceId = presenceId;
            }
            this.SkipModule = skipModule;
            // use default value if no "status" provided
            if (status == null)
            {
                this.Status = StatusEnum.Idle;
            }
            else
            {
                this.Status = status;
            }
        }
        
        /// <summary>
        /// The Presence ID to send a presence notification about
        /// </summary>
        /// <value>The Presence ID to send a presence notification about</value>
        [DataMember(Name="presence_id", EmitDefaultValue=false)]
        public string PresenceId { get; set; }

        /// <summary>
        /// When set to true this callflow action is skipped, advancing to the wildcard branch (if any)
        /// </summary>
        /// <value>When set to true this callflow action is skipped, advancing to the wildcard branch (if any)</value>
        [DataMember(Name="skip_module", EmitDefaultValue=false)]
        public bool? SkipModule { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallflowsManualPresence {\n");
            sb.Append("  PresenceId: ").Append(PresenceId).Append("\n");
            sb.Append("  SkipModule: ").Append(SkipModule).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CallflowsManualPresence);
        }

        /// <summary>
        /// Returns true if CallflowsManualPresence instances are equal
        /// </summary>
        /// <param name="input">Instance of CallflowsManualPresence to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallflowsManualPresence input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PresenceId == input.PresenceId ||
                    (this.PresenceId != null &&
                    this.PresenceId.Equals(input.PresenceId))
                ) && 
                (
                    this.SkipModule == input.SkipModule ||
                    (this.SkipModule != null &&
                    this.SkipModule.Equals(input.SkipModule))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PresenceId != null)
                    hashCode = hashCode * 59 + this.PresenceId.GetHashCode();
                if (this.SkipModule != null)
                    hashCode = hashCode * 59 + this.SkipModule.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
