/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AMQP API for acdc_agent.sync_resp
    /// </summary>
    [DataContract]
    public partial class KapiAcdcAgentSyncResp :  IEquatable<KapiAcdcAgentSyncResp>, IValidatableObject
    {
        /// <summary>
        /// Defines EventCategory
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventCategoryEnum
        {
            
            /// <summary>
            /// Enum Agent for value: agent
            /// </summary>
            [EnumMember(Value = "agent")]
            Agent = 1
        }

        /// <summary>
        /// Gets or Sets EventCategory
        /// </summary>
        [DataMember(Name="Event-Category", EmitDefaultValue=false)]
        public EventCategoryEnum? EventCategory { get; set; }
        /// <summary>
        /// Defines EventName
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventNameEnum
        {
            
            /// <summary>
            /// Enum Syncresp for value: sync_resp
            /// </summary>
            [EnumMember(Value = "sync_resp")]
            Syncresp = 1
        }

        /// <summary>
        /// Gets or Sets EventName
        /// </summary>
        [DataMember(Name="Event-Name", EmitDefaultValue=false)]
        public EventNameEnum? EventName { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum Init for value: init
            /// </summary>
            [EnumMember(Value = "init")]
            Init = 1,
            
            /// <summary>
            /// Enum Sync for value: sync
            /// </summary>
            [EnumMember(Value = "sync")]
            Sync = 2,
            
            /// <summary>
            /// Enum Ready for value: ready
            /// </summary>
            [EnumMember(Value = "ready")]
            Ready = 3,
            
            /// <summary>
            /// Enum Waiting for value: waiting
            /// </summary>
            [EnumMember(Value = "waiting")]
            Waiting = 4,
            
            /// <summary>
            /// Enum Ringing for value: ringing
            /// </summary>
            [EnumMember(Value = "ringing")]
            Ringing = 5,
            
            /// <summary>
            /// Enum Answered for value: answered
            /// </summary>
            [EnumMember(Value = "answered")]
            Answered = 6,
            
            /// <summary>
            /// Enum Wrapup for value: wrapup
            /// </summary>
            [EnumMember(Value = "wrapup")]
            Wrapup = 7,
            
            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            [EnumMember(Value = "paused")]
            Paused = 8
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KapiAcdcAgentSyncResp" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KapiAcdcAgentSyncResp() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KapiAcdcAgentSyncResp" /> class.
        /// </summary>
        /// <param name="accountID">accountID (required).</param>
        /// <param name="agentID">agentID (required).</param>
        /// <param name="callID">callID.</param>
        /// <param name="eventCategory">eventCategory.</param>
        /// <param name="eventName">eventName.</param>
        /// <param name="processID">processID.</param>
        /// <param name="status">status (required).</param>
        /// <param name="timeLeft">timeLeft.</param>
        public KapiAcdcAgentSyncResp(string accountID = default(string), string agentID = default(string), string callID = default(string), EventCategoryEnum? eventCategory = default(EventCategoryEnum?), EventNameEnum? eventName = default(EventNameEnum?), string processID = default(string), StatusEnum status = default(StatusEnum), int? timeLeft = default(int?))
        {
            // to ensure "accountID" is required (not null)
            if (accountID == null)
            {
                throw new InvalidDataException("accountID is a required property for KapiAcdcAgentSyncResp and cannot be null");
            }
            else
            {
                this.AccountID = accountID;
            }
            // to ensure "agentID" is required (not null)
            if (agentID == null)
            {
                throw new InvalidDataException("agentID is a required property for KapiAcdcAgentSyncResp and cannot be null");
            }
            else
            {
                this.AgentID = agentID;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for KapiAcdcAgentSyncResp and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            this.CallID = callID;
            this.EventCategory = eventCategory;
            this.EventName = eventName;
            this.ProcessID = processID;
            this.TimeLeft = timeLeft;
        }
        
        /// <summary>
        /// Gets or Sets AccountID
        /// </summary>
        [DataMember(Name="Account-ID", EmitDefaultValue=false)]
        public string AccountID { get; set; }

        /// <summary>
        /// Gets or Sets AgentID
        /// </summary>
        [DataMember(Name="Agent-ID", EmitDefaultValue=false)]
        public string AgentID { get; set; }

        /// <summary>
        /// Gets or Sets CallID
        /// </summary>
        [DataMember(Name="Call-ID", EmitDefaultValue=false)]
        public string CallID { get; set; }



        /// <summary>
        /// Gets or Sets ProcessID
        /// </summary>
        [DataMember(Name="Process-ID", EmitDefaultValue=false)]
        public string ProcessID { get; set; }


        /// <summary>
        /// Gets or Sets TimeLeft
        /// </summary>
        [DataMember(Name="Time-Left", EmitDefaultValue=false)]
        public int? TimeLeft { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KapiAcdcAgentSyncResp {\n");
            sb.Append("  AccountID: ").Append(AccountID).Append("\n");
            sb.Append("  AgentID: ").Append(AgentID).Append("\n");
            sb.Append("  CallID: ").Append(CallID).Append("\n");
            sb.Append("  EventCategory: ").Append(EventCategory).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("  ProcessID: ").Append(ProcessID).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TimeLeft: ").Append(TimeLeft).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as KapiAcdcAgentSyncResp);
        }

        /// <summary>
        /// Returns true if KapiAcdcAgentSyncResp instances are equal
        /// </summary>
        /// <param name="input">Instance of KapiAcdcAgentSyncResp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KapiAcdcAgentSyncResp input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AccountID == input.AccountID ||
                    (this.AccountID != null &&
                    this.AccountID.Equals(input.AccountID))
                ) && 
                (
                    this.AgentID == input.AgentID ||
                    (this.AgentID != null &&
                    this.AgentID.Equals(input.AgentID))
                ) && 
                (
                    this.CallID == input.CallID ||
                    (this.CallID != null &&
                    this.CallID.Equals(input.CallID))
                ) && 
                (
                    this.EventCategory == input.EventCategory ||
                    (this.EventCategory != null &&
                    this.EventCategory.Equals(input.EventCategory))
                ) && 
                (
                    this.EventName == input.EventName ||
                    (this.EventName != null &&
                    this.EventName.Equals(input.EventName))
                ) && 
                (
                    this.ProcessID == input.ProcessID ||
                    (this.ProcessID != null &&
                    this.ProcessID.Equals(input.ProcessID))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.TimeLeft == input.TimeLeft ||
                    (this.TimeLeft != null &&
                    this.TimeLeft.Equals(input.TimeLeft))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountID != null)
                    hashCode = hashCode * 59 + this.AccountID.GetHashCode();
                if (this.AgentID != null)
                    hashCode = hashCode * 59 + this.AgentID.GetHashCode();
                if (this.CallID != null)
                    hashCode = hashCode * 59 + this.CallID.GetHashCode();
                if (this.EventCategory != null)
                    hashCode = hashCode * 59 + this.EventCategory.GetHashCode();
                if (this.EventName != null)
                    hashCode = hashCode * 59 + this.EventName.GetHashCode();
                if (this.ProcessID != null)
                    hashCode = hashCode * 59 + this.ProcessID.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.TimeLeft != null)
                    hashCode = hashCode * 59 + this.TimeLeft.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
