/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Schema for kazoo.pdf system_config
    /// </summary>
    [DataContract]
    public partial class SystemConfigKazooPdf :  IEquatable<SystemConfigKazooPdf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigKazooPdf" /> class.
        /// </summary>
        /// <param name="html2pdf">kazoo.pdf html2pdf (default to &quot;/usr/bin/htmldoc --quiet --webpage -f $pdf$ $html$&quot;).</param>
        public SystemConfigKazooPdf(string html2pdf = "/usr/bin/htmldoc --quiet --webpage -f $pdf$ $html$")
        {
            // use default value if no "html2pdf" provided
            if (html2pdf == null)
            {
                this.Html2pdf = "/usr/bin/htmldoc --quiet --webpage -f $pdf$ $html$";
            }
            else
            {
                this.Html2pdf = html2pdf;
            }
        }
        
        /// <summary>
        /// kazoo.pdf html2pdf
        /// </summary>
        /// <value>kazoo.pdf html2pdf</value>
        [DataMember(Name="html2pdf", EmitDefaultValue=false)]
        public string Html2pdf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SystemConfigKazooPdf {\n");
            sb.Append("  Html2pdf: ").Append(Html2pdf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SystemConfigKazooPdf);
        }

        /// <summary>
        /// Returns true if SystemConfigKazooPdf instances are equal
        /// </summary>
        /// <param name="input">Instance of SystemConfigKazooPdf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SystemConfigKazooPdf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Html2pdf == input.Html2pdf ||
                    (this.Html2pdf != null &&
                    this.Html2pdf.Equals(input.Html2pdf))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Html2pdf != null)
                    hashCode = hashCode * 59 + this.Html2pdf.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
