/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountConfigConferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountConfigConferencesTests
    {
        // TODO uncomment below to declare an instance variable for AccountConfigConferences
        //private AccountConfigConferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountConfigConferences
            //instance = new AccountConfigConferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountConfigConferences
        /// </summary>
        [Test]
        public void AccountConfigConferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountConfigConferences
            //Assert.IsInstanceOfType<AccountConfigConferences> (instance, "variable 'instance' is a AccountConfigConferences");
        }


        /// <summary>
        /// Test the property 'Controls'
        /// </summary>
        [Test]
        public void ControlsTest()
        {
            // TODO unit test for the property 'Controls'
        }
        /// <summary>
        /// Test the property 'EntryTone'
        /// </summary>
        [Test]
        public void EntryToneTest()
        {
            // TODO unit test for the property 'EntryTone'
        }
        /// <summary>
        /// Test the property 'ExitTone'
        /// </summary>
        [Test]
        public void ExitToneTest()
        {
            // TODO unit test for the property 'ExitTone'
        }
        /// <summary>
        /// Test the property 'ModeratorEntryTone'
        /// </summary>
        [Test]
        public void ModeratorEntryToneTest()
        {
            // TODO unit test for the property 'ModeratorEntryTone'
        }
        /// <summary>
        /// Test the property 'ModeratorExitTone'
        /// </summary>
        [Test]
        public void ModeratorExitToneTest()
        {
            // TODO unit test for the property 'ModeratorExitTone'
        }
        /// <summary>
        /// Test the property 'NumberTimeout'
        /// </summary>
        [Test]
        public void NumberTimeoutTest()
        {
            // TODO unit test for the property 'NumberTimeout'
        }
        /// <summary>
        /// Test the property 'PinTimeout'
        /// </summary>
        [Test]
        public void PinTimeoutTest()
        {
            // TODO unit test for the property 'PinTimeout'
        }
        /// <summary>
        /// Test the property 'SupportNameAnnouncement'
        /// </summary>
        [Test]
        public void SupportNameAnnouncementTest()
        {
            // TODO unit test for the property 'SupportNameAnnouncement'
        }

    }

}
