/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallflowsAcdcAgent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallflowsAcdcAgentTests
    {
        // TODO uncomment below to declare an instance variable for CallflowsAcdcAgent
        //private CallflowsAcdcAgent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallflowsAcdcAgent
            //instance = new CallflowsAcdcAgent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallflowsAcdcAgent
        /// </summary>
        [Test]
        public void CallflowsAcdcAgentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallflowsAcdcAgent
            //Assert.IsInstanceOfType<CallflowsAcdcAgent> (instance, "variable 'instance' is a CallflowsAcdcAgent");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'PresenceId'
        /// </summary>
        [Test]
        public void PresenceIdTest()
        {
            // TODO unit test for the property 'PresenceId'
        }
        /// <summary>
        /// Test the property 'PresenceState'
        /// </summary>
        [Test]
        public void PresenceStateTest()
        {
            // TODO unit test for the property 'PresenceState'
        }
        /// <summary>
        /// Test the property 'SkipModule'
        /// </summary>
        [Test]
        public void SkipModuleTest()
        {
            // TODO unit test for the property 'SkipModule'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }

    }

}
