/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallflowsIntercept
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallflowsInterceptTests
    {
        // TODO uncomment below to declare an instance variable for CallflowsIntercept
        //private CallflowsIntercept instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallflowsIntercept
            //instance = new CallflowsIntercept();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallflowsIntercept
        /// </summary>
        [Test]
        public void CallflowsInterceptInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallflowsIntercept
            //Assert.IsInstanceOfType<CallflowsIntercept> (instance, "variable 'instance' is a CallflowsIntercept");
        }


        /// <summary>
        /// Test the property 'ApprovedDeviceId'
        /// </summary>
        [Test]
        public void ApprovedDeviceIdTest()
        {
            // TODO unit test for the property 'ApprovedDeviceId'
        }
        /// <summary>
        /// Test the property 'ApprovedGroupId'
        /// </summary>
        [Test]
        public void ApprovedGroupIdTest()
        {
            // TODO unit test for the property 'ApprovedGroupId'
        }
        /// <summary>
        /// Test the property 'ApprovedUserId'
        /// </summary>
        [Test]
        public void ApprovedUserIdTest()
        {
            // TODO unit test for the property 'ApprovedUserId'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'SkipModule'
        /// </summary>
        [Test]
        public void SkipModuleTest()
        {
            // TODO unit test for the property 'SkipModule'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
