/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallflowsPrivacy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallflowsPrivacyTests
    {
        // TODO uncomment below to declare an instance variable for CallflowsPrivacy
        //private CallflowsPrivacy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallflowsPrivacy
            //instance = new CallflowsPrivacy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallflowsPrivacy
        /// </summary>
        [Test]
        public void CallflowsPrivacyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallflowsPrivacy
            //Assert.IsInstanceOfType<CallflowsPrivacy> (instance, "variable 'instance' is a CallflowsPrivacy");
        }


        /// <summary>
        /// Test the property 'EndpointStrategy'
        /// </summary>
        [Test]
        public void EndpointStrategyTest()
        {
            // TODO unit test for the property 'EndpointStrategy'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'SkipModule'
        /// </summary>
        [Test]
        public void SkipModuleTest()
        {
            // TODO unit test for the property 'SkipModule'
        }

    }

}
