/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallflowsMenu
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallflowsMenuTests
    {
        // TODO uncomment below to declare an instance variable for CallflowsMenu
        //private CallflowsMenu instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallflowsMenu
            //instance = new CallflowsMenu();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallflowsMenu
        /// </summary>
        [Test]
        public void CallflowsMenuInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallflowsMenu
            //Assert.IsInstanceOfType<CallflowsMenu> (instance, "variable 'instance' is a CallflowsMenu");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InterdigitTimeout'
        /// </summary>
        [Test]
        public void InterdigitTimeoutTest()
        {
            // TODO unit test for the property 'InterdigitTimeout'
        }
        /// <summary>
        /// Test the property 'SkipModule'
        /// </summary>
        [Test]
        public void SkipModuleTest()
        {
            // TODO unit test for the property 'SkipModule'
        }

    }

}
