/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeviceRateLimitsPerSecond
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceRateLimitsPerSecondTests
    {
        // TODO uncomment below to declare an instance variable for DeviceRateLimitsPerSecond
        //private DeviceRateLimitsPerSecond instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceRateLimitsPerSecond
            //instance = new DeviceRateLimitsPerSecond();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceRateLimitsPerSecond
        /// </summary>
        [Test]
        public void DeviceRateLimitsPerSecondInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceRateLimitsPerSecond
            //Assert.IsInstanceOfType<DeviceRateLimitsPerSecond> (instance, "variable 'instance' is a DeviceRateLimitsPerSecond");
        }


        /// <summary>
        /// Test the property 'Invites'
        /// </summary>
        [Test]
        public void InvitesTest()
        {
            // TODO unit test for the property 'Invites'
        }
        /// <summary>
        /// Test the property 'Registrations'
        /// </summary>
        [Test]
        public void RegistrationsTest()
        {
            // TODO unit test for the property 'Registrations'
        }
        /// <summary>
        /// Test the property 'TotalPackets'
        /// </summary>
        [Test]
        public void TotalPacketsTest()
        {
            // TODO unit test for the property 'TotalPackets'
        }

    }

}
