/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiNotificationsWebhookDisabled
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiNotificationsWebhookDisabledTests
    {
        // TODO uncomment below to declare an instance variable for KapiNotificationsWebhookDisabled
        //private KapiNotificationsWebhookDisabled instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiNotificationsWebhookDisabled
            //instance = new KapiNotificationsWebhookDisabled();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiNotificationsWebhookDisabled
        /// </summary>
        [Test]
        public void KapiNotificationsWebhookDisabledInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiNotificationsWebhookDisabled
            //Assert.IsInstanceOfType<KapiNotificationsWebhookDisabled> (instance, "variable 'instance' is a KapiNotificationsWebhookDisabled");
        }


        /// <summary>
        /// Test the property 'AccountDB'
        /// </summary>
        [Test]
        public void AccountDBTest()
        {
            // TODO unit test for the property 'AccountDB'
        }
        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Test]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'AttachmentURL'
        /// </summary>
        [Test]
        public void AttachmentURLTest()
        {
            // TODO unit test for the property 'AttachmentURL'
        }
        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Test]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }
        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Test]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'HTML'
        /// </summary>
        [Test]
        public void HTMLTest()
        {
            // TODO unit test for the property 'HTML'
        }
        /// <summary>
        /// Test the property 'HookID'
        /// </summary>
        [Test]
        public void HookIDTest()
        {
            // TODO unit test for the property 'HookID'
        }
        /// <summary>
        /// Test the property 'Preview'
        /// </summary>
        [Test]
        public void PreviewTest()
        {
            // TODO unit test for the property 'Preview'
        }
        /// <summary>
        /// Test the property 'ReplyTo'
        /// </summary>
        [Test]
        public void ReplyToTest()
        {
            // TODO unit test for the property 'ReplyTo'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
