/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiXmppEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiXmppEventTests
    {
        // TODO uncomment below to declare an instance variable for KapiXmppEvent
        //private KapiXmppEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiXmppEvent
            //instance = new KapiXmppEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiXmppEvent
        /// </summary>
        [Test]
        public void KapiXmppEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiXmppEvent
            //Assert.IsInstanceOfType<KapiXmppEvent> (instance, "variable 'instance' is a KapiXmppEvent");
        }


        /// <summary>
        /// Test the property 'ApplicationData'
        /// </summary>
        [Test]
        public void ApplicationDataTest()
        {
            // TODO unit test for the property 'ApplicationData'
        }
        /// <summary>
        /// Test the property 'ApplicationEvent'
        /// </summary>
        [Test]
        public void ApplicationEventTest()
        {
            // TODO unit test for the property 'ApplicationEvent'
        }
        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Test]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'JID'
        /// </summary>
        [Test]
        public void JIDTest()
        {
            // TODO unit test for the property 'JID'
        }

    }

}
