/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiAsrReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiAsrReqTests
    {
        // TODO uncomment below to declare an instance variable for KapiAsrReq
        //private KapiAsrReq instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiAsrReq
            //instance = new KapiAsrReq();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiAsrReq
        /// </summary>
        [Test]
        public void KapiAsrReqInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiAsrReq
            //Assert.IsInstanceOfType<KapiAsrReq> (instance, "variable 'instance' is a KapiAsrReq");
        }


        /// <summary>
        /// Test the property 'ASRAccountID'
        /// </summary>
        [Test]
        public void ASRAccountIDTest()
        {
            // TODO unit test for the property 'ASRAccountID'
        }
        /// <summary>
        /// Test the property 'ASRAccountPassword'
        /// </summary>
        [Test]
        public void ASRAccountPasswordTest()
        {
            // TODO unit test for the property 'ASRAccountPassword'
        }
        /// <summary>
        /// Test the property 'ASREndpoint'
        /// </summary>
        [Test]
        public void ASREndpointTest()
        {
            // TODO unit test for the property 'ASREndpoint'
        }
        /// <summary>
        /// Test the property 'CallID'
        /// </summary>
        [Test]
        public void CallIDTest()
        {
            // TODO unit test for the property 'CallID'
        }
        /// <summary>
        /// Test the property 'ControlQueue'
        /// </summary>
        [Test]
        public void ControlQueueTest()
        {
            // TODO unit test for the property 'ControlQueue'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'StreamResponse'
        /// </summary>
        [Test]
        public void StreamResponseTest()
        {
            // TODO unit test for the property 'StreamResponse'
        }

    }

}
