/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiRegistrationQueryErr
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiRegistrationQueryErrTests
    {
        // TODO uncomment below to declare an instance variable for KapiRegistrationQueryErr
        //private KapiRegistrationQueryErr instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiRegistrationQueryErr
            //instance = new KapiRegistrationQueryErr();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiRegistrationQueryErr
        /// </summary>
        [Test]
        public void KapiRegistrationQueryErrInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiRegistrationQueryErr
            //Assert.IsInstanceOfType<KapiRegistrationQueryErr> (instance, "variable 'instance' is a KapiRegistrationQueryErr");
        }


        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'RegistrarAge'
        /// </summary>
        [Test]
        public void RegistrarAgeTest()
        {
            // TODO unit test for the property 'RegistrarAge'
        }

    }

}
