/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiNodesAdvertise
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiNodesAdvertiseTests
    {
        // TODO uncomment below to declare an instance variable for KapiNodesAdvertise
        //private KapiNodesAdvertise instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiNodesAdvertise
            //instance = new KapiNodesAdvertise();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiNodesAdvertise
        /// </summary>
        [Test]
        public void KapiNodesAdvertiseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiNodesAdvertise
            //Assert.IsInstanceOfType<KapiNodesAdvertise> (instance, "variable 'instance' is a KapiNodesAdvertise");
        }


        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Test]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }
        /// <summary>
        /// Test the property 'Conferences'
        /// </summary>
        [Test]
        public void ConferencesTest()
        {
            // TODO unit test for the property 'Conferences'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'Expires'
        /// </summary>
        [Test]
        public void ExpiresTest()
        {
            // TODO unit test for the property 'Expires'
        }
        /// <summary>
        /// Test the property 'Globals'
        /// </summary>
        [Test]
        public void GlobalsTest()
        {
            // TODO unit test for the property 'Globals'
        }
        /// <summary>
        /// Test the property 'MediaServers'
        /// </summary>
        [Test]
        public void MediaServersTest()
        {
            // TODO unit test for the property 'MediaServers'
        }
        /// <summary>
        /// Test the property 'NodeInfo'
        /// </summary>
        [Test]
        public void NodeInfoTest()
        {
            // TODO unit test for the property 'NodeInfo'
        }
        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Test]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }
        /// <summary>
        /// Test the property 'Processes'
        /// </summary>
        [Test]
        public void ProcessesTest()
        {
            // TODO unit test for the property 'Processes'
        }
        /// <summary>
        /// Test the property 'Registrations'
        /// </summary>
        [Test]
        public void RegistrationsTest()
        {
            // TODO unit test for the property 'Registrations'
        }
        /// <summary>
        /// Test the property 'UsedMemory'
        /// </summary>
        [Test]
        public void UsedMemoryTest()
        {
            // TODO unit test for the property 'UsedMemory'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'WhApps'
        /// </summary>
        [Test]
        public void WhAppsTest()
        {
            // TODO unit test for the property 'WhApps'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }
        /// <summary>
        /// Test the property 'Md5'
        /// </summary>
        [Test]
        public void Md5Test()
        {
            // TODO unit test for the property 'Md5'
        }

    }

}
