/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiAcdcQueueMemberConnectAccepted
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiAcdcQueueMemberConnectAcceptedTests
    {
        // TODO uncomment below to declare an instance variable for KapiAcdcQueueMemberConnectAccepted
        //private KapiAcdcQueueMemberConnectAccepted instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiAcdcQueueMemberConnectAccepted
            //instance = new KapiAcdcQueueMemberConnectAccepted();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiAcdcQueueMemberConnectAccepted
        /// </summary>
        [Test]
        public void KapiAcdcQueueMemberConnectAcceptedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiAcdcQueueMemberConnectAccepted
            //Assert.IsInstanceOfType<KapiAcdcQueueMemberConnectAccepted> (instance, "variable 'instance' is a KapiAcdcQueueMemberConnectAccepted");
        }


        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Test]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'AgentID'
        /// </summary>
        [Test]
        public void AgentIDTest()
        {
            // TODO unit test for the property 'AgentID'
        }
        /// <summary>
        /// Test the property 'CallID'
        /// </summary>
        [Test]
        public void CallIDTest()
        {
            // TODO unit test for the property 'CallID'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'ProcessID'
        /// </summary>
        [Test]
        public void ProcessIDTest()
        {
            // TODO unit test for the property 'ProcessID'
        }

    }

}
