/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiDialplanTonesReqToneHeaders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiDialplanTonesReqToneHeadersTests
    {
        // TODO uncomment below to declare an instance variable for KapiDialplanTonesReqToneHeaders
        //private KapiDialplanTonesReqToneHeaders instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiDialplanTonesReqToneHeaders
            //instance = new KapiDialplanTonesReqToneHeaders();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiDialplanTonesReqToneHeaders
        /// </summary>
        [Test]
        public void KapiDialplanTonesReqToneHeadersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiDialplanTonesReqToneHeaders
            //Assert.IsInstanceOfType<KapiDialplanTonesReqToneHeaders> (instance, "variable 'instance' is a KapiDialplanTonesReqToneHeaders");
        }


        /// <summary>
        /// Test the property 'DurationOFF'
        /// </summary>
        [Test]
        public void DurationOFFTest()
        {
            // TODO unit test for the property 'DurationOFF'
        }
        /// <summary>
        /// Test the property 'DurationON'
        /// </summary>
        [Test]
        public void DurationONTest()
        {
            // TODO unit test for the property 'DurationON'
        }
        /// <summary>
        /// Test the property 'Frequencies'
        /// </summary>
        [Test]
        public void FrequenciesTest()
        {
            // TODO unit test for the property 'Frequencies'
        }
        /// <summary>
        /// Test the property 'Repeat'
        /// </summary>
        [Test]
        public void RepeatTest()
        {
            // TODO unit test for the property 'Repeat'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Test]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }

    }

}
