/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiAcdcStatsAverageWaitTimeResp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiAcdcStatsAverageWaitTimeRespTests
    {
        // TODO uncomment below to declare an instance variable for KapiAcdcStatsAverageWaitTimeResp
        //private KapiAcdcStatsAverageWaitTimeResp instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiAcdcStatsAverageWaitTimeResp
            //instance = new KapiAcdcStatsAverageWaitTimeResp();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiAcdcStatsAverageWaitTimeResp
        /// </summary>
        [Test]
        public void KapiAcdcStatsAverageWaitTimeRespInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiAcdcStatsAverageWaitTimeResp
            //Assert.IsInstanceOfType<KapiAcdcStatsAverageWaitTimeResp> (instance, "variable 'instance' is a KapiAcdcStatsAverageWaitTimeResp");
        }


        /// <summary>
        /// Test the property 'AverageWaitTime'
        /// </summary>
        [Test]
        public void AverageWaitTimeTest()
        {
            // TODO unit test for the property 'AverageWaitTime'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }

    }

}
