/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiFaxStartJob
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiFaxStartJobTests
    {
        // TODO uncomment below to declare an instance variable for KapiFaxStartJob
        //private KapiFaxStartJob instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiFaxStartJob
            //instance = new KapiFaxStartJob();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiFaxStartJob
        /// </summary>
        [Test]
        public void KapiFaxStartJobInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiFaxStartJob
            //Assert.IsInstanceOfType<KapiFaxStartJob> (instance, "variable 'instance' is a KapiFaxStartJob");
        }


        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Test]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'ControlQueue'
        /// </summary>
        [Test]
        public void ControlQueueTest()
        {
            // TODO unit test for the property 'ControlQueue'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Test]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }
        /// <summary>
        /// Test the property 'ToNumber'
        /// </summary>
        [Test]
        public void ToNumberTest()
        {
            // TODO unit test for the property 'ToNumber'
        }

    }

}
