/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiAcdcStatsStatusOutbound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiAcdcStatsStatusOutboundTests
    {
        // TODO uncomment below to declare an instance variable for KapiAcdcStatsStatusOutbound
        //private KapiAcdcStatsStatusOutbound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiAcdcStatsStatusOutbound
            //instance = new KapiAcdcStatsStatusOutbound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiAcdcStatsStatusOutbound
        /// </summary>
        [Test]
        public void KapiAcdcStatsStatusOutboundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiAcdcStatsStatusOutbound
            //Assert.IsInstanceOfType<KapiAcdcStatsStatusOutbound> (instance, "variable 'instance' is a KapiAcdcStatsStatusOutbound");
        }


        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Test]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'AgentID'
        /// </summary>
        [Test]
        public void AgentIDTest()
        {
            // TODO unit test for the property 'AgentID'
        }
        /// <summary>
        /// Test the property 'CallID'
        /// </summary>
        [Test]
        public void CallIDTest()
        {
            // TODO unit test for the property 'CallID'
        }
        /// <summary>
        /// Test the property 'CallerIDName'
        /// </summary>
        [Test]
        public void CallerIDNameTest()
        {
            // TODO unit test for the property 'CallerIDName'
        }
        /// <summary>
        /// Test the property 'CallerIDNumber'
        /// </summary>
        [Test]
        public void CallerIDNumberTest()
        {
            // TODO unit test for the property 'CallerIDNumber'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'PauseTime'
        /// </summary>
        [Test]
        public void PauseTimeTest()
        {
            // TODO unit test for the property 'PauseTime'
        }
        /// <summary>
        /// Test the property 'QueueID'
        /// </summary>
        [Test]
        public void QueueIDTest()
        {
            // TODO unit test for the property 'QueueID'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'WaitTime'
        /// </summary>
        [Test]
        public void WaitTimeTest()
        {
            // TODO unit test for the property 'WaitTime'
        }

    }

}
