/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiDialplanBreak
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiDialplanBreakTests
    {
        // TODO uncomment below to declare an instance variable for KapiDialplanBreak
        //private KapiDialplanBreak instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiDialplanBreak
            //instance = new KapiDialplanBreak();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiDialplanBreak
        /// </summary>
        [Test]
        public void KapiDialplanBreakInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiDialplanBreak
            //Assert.IsInstanceOfType<KapiDialplanBreak> (instance, "variable 'instance' is a KapiDialplanBreak");
        }


        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Test]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'CallID'
        /// </summary>
        [Test]
        public void CallIDTest()
        {
            // TODO unit test for the property 'CallID'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'InsertAt'
        /// </summary>
        [Test]
        public void InsertAtTest()
        {
            // TODO unit test for the property 'InsertAt'
        }

    }

}
