/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing KapiPivotReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KapiPivotReqTests
    {
        // TODO uncomment below to declare an instance variable for KapiPivotReq
        //private KapiPivotReq instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KapiPivotReq
            //instance = new KapiPivotReq();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KapiPivotReq
        /// </summary>
        [Test]
        public void KapiPivotReqInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KapiPivotReq
            //Assert.IsInstanceOfType<KapiPivotReq> (instance, "variable 'instance' is a KapiPivotReq");
        }


        /// <summary>
        /// Test the property 'CDR_URI'
        /// </summary>
        [Test]
        public void CDR_URITest()
        {
            // TODO unit test for the property 'CDR_URI'
        }
        /// <summary>
        /// Test the property 'Call'
        /// </summary>
        [Test]
        public void CallTest()
        {
            // TODO unit test for the property 'Call'
        }
        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Test]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }
        /// <summary>
        /// Test the property 'EventCategory'
        /// </summary>
        [Test]
        public void EventCategoryTest()
        {
            // TODO unit test for the property 'EventCategory'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'HTTPMethod'
        /// </summary>
        [Test]
        public void HTTPMethodTest()
        {
            // TODO unit test for the property 'HTTPMethod'
        }
        /// <summary>
        /// Test the property 'RequestBodyFormat'
        /// </summary>
        [Test]
        public void RequestBodyFormatTest()
        {
            // TODO unit test for the property 'RequestBodyFormat'
        }
        /// <summary>
        /// Test the property 'RequestFormat'
        /// </summary>
        [Test]
        public void RequestFormatTest()
        {
            // TODO unit test for the property 'RequestFormat'
        }
        /// <summary>
        /// Test the property 'VoiceURI'
        /// </summary>
        [Test]
        public void VoiceURITest()
        {
            // TODO unit test for the property 'VoiceURI'
        }

    }

}
