/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Profile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProfileTests
    {
        // TODO uncomment below to declare an instance variable for Profile
        //private Profile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Profile
            //instance = new Profile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Profile
        /// </summary>
        [Test]
        public void ProfileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Profile
            //Assert.IsInstanceOfType<Profile> (instance, "variable 'instance' is a Profile");
        }


        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Test]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }
        /// <summary>
        /// Test the property 'Assistant'
        /// </summary>
        [Test]
        public void AssistantTest()
        {
            // TODO unit test for the property 'Assistant'
        }
        /// <summary>
        /// Test the property 'Birthday'
        /// </summary>
        [Test]
        public void BirthdayTest()
        {
            // TODO unit test for the property 'Birthday'
        }
        /// <summary>
        /// Test the property 'Nicknames'
        /// </summary>
        [Test]
        public void NicknamesTest()
        {
            // TODO unit test for the property 'Nicknames'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'SortString'
        /// </summary>
        [Test]
        public void SortStringTest()
        {
            // TODO unit test for the property 'SortString'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
