/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServicePlanItemDiscountsCumulative
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServicePlanItemDiscountsCumulativeTests
    {
        // TODO uncomment below to declare an instance variable for ServicePlanItemDiscountsCumulative
        //private ServicePlanItemDiscountsCumulative instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServicePlanItemDiscountsCumulative
            //instance = new ServicePlanItemDiscountsCumulative();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServicePlanItemDiscountsCumulative
        /// </summary>
        [Test]
        public void ServicePlanItemDiscountsCumulativeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServicePlanItemDiscountsCumulative
            //Assert.IsInstanceOfType<ServicePlanItemDiscountsCumulative> (instance, "variable 'instance' is a ServicePlanItemDiscountsCumulative");
        }


        /// <summary>
        /// Test the property 'Maximum'
        /// </summary>
        [Test]
        public void MaximumTest()
        {
            // TODO unit test for the property 'Maximum'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Test]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }

    }

}
