/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StorageAttachmentDropbox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageAttachmentDropboxTests
    {
        // TODO uncomment below to declare an instance variable for StorageAttachmentDropbox
        //private StorageAttachmentDropbox instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorageAttachmentDropbox
            //instance = new StorageAttachmentDropbox();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorageAttachmentDropbox
        /// </summary>
        [Test]
        public void StorageAttachmentDropboxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StorageAttachmentDropbox
            //Assert.IsInstanceOfType<StorageAttachmentDropbox> (instance, "variable 'instance' is a StorageAttachmentDropbox");
        }


        /// <summary>
        /// Test the property 'Handler'
        /// </summary>
        [Test]
        public void HandlerTest()
        {
            // TODO unit test for the property 'Handler'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

    }

}
