/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StorageAttachmentGoogleDriveSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageAttachmentGoogleDriveSettingsTests
    {
        // TODO uncomment below to declare an instance variable for StorageAttachmentGoogleDriveSettings
        //private StorageAttachmentGoogleDriveSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorageAttachmentGoogleDriveSettings
            //instance = new StorageAttachmentGoogleDriveSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorageAttachmentGoogleDriveSettings
        /// </summary>
        [Test]
        public void StorageAttachmentGoogleDriveSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StorageAttachmentGoogleDriveSettings
            //Assert.IsInstanceOfType<StorageAttachmentGoogleDriveSettings> (instance, "variable 'instance' is a StorageAttachmentGoogleDriveSettings");
        }


        /// <summary>
        /// Test the property 'FolderId'
        /// </summary>
        [Test]
        public void FolderIdTest()
        {
            // TODO unit test for the property 'FolderId'
        }
        /// <summary>
        /// Test the property 'OauthDocId'
        /// </summary>
        [Test]
        public void OauthDocIdTest()
        {
            // TODO unit test for the property 'OauthDocId'
        }

    }

}
