/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SystemConfigNumberManagerDashE911
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemConfigNumberManagerDashE911Tests
    {
        // TODO uncomment below to declare an instance variable for SystemConfigNumberManagerDashE911
        //private SystemConfigNumberManagerDashE911 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemConfigNumberManagerDashE911
            //instance = new SystemConfigNumberManagerDashE911();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemConfigNumberManagerDashE911
        /// </summary>
        [Test]
        public void SystemConfigNumberManagerDashE911InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemConfigNumberManagerDashE911
            //Assert.IsInstanceOfType<SystemConfigNumberManagerDashE911> (instance, "variable 'instance' is a SystemConfigNumberManagerDashE911");
        }


        /// <summary>
        /// Test the property 'AuthPassword'
        /// </summary>
        [Test]
        public void AuthPasswordTest()
        {
            // TODO unit test for the property 'AuthPassword'
        }
        /// <summary>
        /// Test the property 'AuthUsername'
        /// </summary>
        [Test]
        public void AuthUsernameTest()
        {
            // TODO unit test for the property 'AuthUsername'
        }
        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Test]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }
        /// <summary>
        /// Test the property 'EmergencyProvisioningUrl'
        /// </summary>
        [Test]
        public void EmergencyProvisioningUrlTest()
        {
            // TODO unit test for the property 'EmergencyProvisioningUrl'
        }

    }

}
