/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SystemConfigCrossbarOnboard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemConfigCrossbarOnboardTests
    {
        // TODO uncomment below to declare an instance variable for SystemConfigCrossbarOnboard
        //private SystemConfigCrossbarOnboard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemConfigCrossbarOnboard
            //instance = new SystemConfigCrossbarOnboard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemConfigCrossbarOnboard
        /// </summary>
        [Test]
        public void SystemConfigCrossbarOnboardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemConfigCrossbarOnboard
            //Assert.IsInstanceOfType<SystemConfigCrossbarOnboard> (instance, "variable 'instance' is a SystemConfigCrossbarOnboard");
        }


        /// <summary>
        /// Test the property 'DefaultCallflowStartExten'
        /// </summary>
        [Test]
        public void DefaultCallflowStartExtenTest()
        {
            // TODO unit test for the property 'DefaultCallflowStartExten'
        }
        /// <summary>
        /// Test the property 'DefaultExtensionCallflow'
        /// </summary>
        [Test]
        public void DefaultExtensionCallflowTest()
        {
            // TODO unit test for the property 'DefaultExtensionCallflow'
        }
        /// <summary>
        /// Test the property 'DefaultVmStartExten'
        /// </summary>
        [Test]
        public void DefaultVmStartExtenTest()
        {
            // TODO unit test for the property 'DefaultVmStartExten'
        }
        /// <summary>
        /// Test the property 'DevicePwdStrength'
        /// </summary>
        [Test]
        public void DevicePwdStrengthTest()
        {
            // TODO unit test for the property 'DevicePwdStrength'
        }
        /// <summary>
        /// Test the property 'DeviceUsernameStrength'
        /// </summary>
        [Test]
        public void DeviceUsernameStrengthTest()
        {
            // TODO unit test for the property 'DeviceUsernameStrength'
        }

    }

}
