/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SystemConfigDoodle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemConfigDoodleTests
    {
        // TODO uncomment below to declare an instance variable for SystemConfigDoodle
        //private SystemConfigDoodle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemConfigDoodle
            //instance = new SystemConfigDoodle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemConfigDoodle
        /// </summary>
        [Test]
        public void SystemConfigDoodleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemConfigDoodle
            //Assert.IsInstanceOfType<SystemConfigDoodle> (instance, "variable 'instance' is a SystemConfigDoodle");
        }


        /// <summary>
        /// Test the property 'ApiPreserveCallerId'
        /// </summary>
        [Test]
        public void ApiPreserveCallerIdTest()
        {
            // TODO unit test for the property 'ApiPreserveCallerId'
        }
        /// <summary>
        /// Test the property 'Connections'
        /// </summary>
        [Test]
        public void ConnectionsTest()
        {
            // TODO unit test for the property 'Connections'
        }
        /// <summary>
        /// Test the property 'DefaultTestFromNumber'
        /// </summary>
        [Test]
        public void DefaultTestFromNumberTest()
        {
            // TODO unit test for the property 'DefaultTestFromNumber'
        }
        /// <summary>
        /// Test the property 'DefaultTestRouteId'
        /// </summary>
        [Test]
        public void DefaultTestRouteIdTest()
        {
            // TODO unit test for the property 'DefaultTestRouteId'
        }
        /// <summary>
        /// Test the property 'InboundBroker'
        /// </summary>
        [Test]
        public void InboundBrokerTest()
        {
            // TODO unit test for the property 'InboundBroker'
        }
        /// <summary>
        /// Test the property 'InboundExchange'
        /// </summary>
        [Test]
        public void InboundExchangeTest()
        {
            // TODO unit test for the property 'InboundExchange'
        }
        /// <summary>
        /// Test the property 'InboundExchangeOptions'
        /// </summary>
        [Test]
        public void InboundExchangeOptionsTest()
        {
            // TODO unit test for the property 'InboundExchangeOptions'
        }
        /// <summary>
        /// Test the property 'InboundExchangeType'
        /// </summary>
        [Test]
        public void InboundExchangeTypeTest()
        {
            // TODO unit test for the property 'InboundExchangeType'
        }
        /// <summary>
        /// Test the property 'InboundQueueName'
        /// </summary>
        [Test]
        public void InboundQueueNameTest()
        {
            // TODO unit test for the property 'InboundQueueName'
        }
        /// <summary>
        /// Test the property 'MinBucketCost'
        /// </summary>
        [Test]
        public void MinBucketCostTest()
        {
            // TODO unit test for the property 'MinBucketCost'
        }
        /// <summary>
        /// Test the property 'Reschedule'
        /// </summary>
        [Test]
        public void RescheduleTest()
        {
            // TODO unit test for the property 'Reschedule'
        }
        /// <summary>
        /// Test the property 'RouteWinTimeout'
        /// </summary>
        [Test]
        public void RouteWinTimeoutTest()
        {
            // TODO unit test for the property 'RouteWinTimeout'
        }
        /// <summary>
        /// Test the property 'UnavailableMessage'
        /// </summary>
        [Test]
        public void UnavailableMessageTest()
        {
            // TODO unit test for the property 'UnavailableMessage'
        }

    }

}
