/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SystemConfigSms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemConfigSmsTests
    {
        // TODO uncomment below to declare an instance variable for SystemConfigSms
        //private SystemConfigSms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemConfigSms
            //instance = new SystemConfigSms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemConfigSms
        /// </summary>
        [Test]
        public void SystemConfigSmsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemConfigSms
            //Assert.IsInstanceOfType<SystemConfigSms> (instance, "variable 'instance' is a SystemConfigSms");
        }


        /// <summary>
        /// Test the property 'Outbound'
        /// </summary>
        [Test]
        public void OutboundTest()
        {
            // TODO unit test for the property 'Outbound'
        }

    }

}
