/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SystemConfigTasksNotifyResend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemConfigTasksNotifyResendTests
    {
        // TODO uncomment below to declare an instance variable for SystemConfigTasksNotifyResend
        //private SystemConfigTasksNotifyResend instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemConfigTasksNotifyResend
            //instance = new SystemConfigTasksNotifyResend();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemConfigTasksNotifyResend
        /// </summary>
        [Test]
        public void SystemConfigTasksNotifyResendInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemConfigTasksNotifyResend
            //Assert.IsInstanceOfType<SystemConfigTasksNotifyResend> (instance, "variable 'instance' is a SystemConfigTasksNotifyResend");
        }


        /// <summary>
        /// Test the property 'CycleDelayTimeMs'
        /// </summary>
        [Test]
        public void CycleDelayTimeMsTest()
        {
            // TODO unit test for the property 'CycleDelayTimeMs'
        }
        /// <summary>
        /// Test the property 'MaxDocRead'
        /// </summary>
        [Test]
        public void MaxDocReadTest()
        {
            // TODO unit test for the property 'MaxDocRead'
        }
        /// <summary>
        /// Test the property 'MaxRetries'
        /// </summary>
        [Test]
        public void MaxRetriesTest()
        {
            // TODO unit test for the property 'MaxRetries'
        }
        /// <summary>
        /// Test the property 'PublishTimeoutMs'
        /// </summary>
        [Test]
        public void PublishTimeoutMsTest()
        {
            // TODO unit test for the property 'PublishTimeoutMs'
        }
        /// <summary>
        /// Test the property 'RescheduleRules'
        /// </summary>
        [Test]
        public void RescheduleRulesTest()
        {
            // TODO unit test for the property 'RescheduleRules'
        }
        /// <summary>
        /// Test the property 'RetryAfterFudgeS'
        /// </summary>
        [Test]
        public void RetryAfterFudgeSTest()
        {
            // TODO unit test for the property 'RetryAfterFudgeS'
        }

    }

}
