/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhookAttempts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookAttemptsTests
    {
        // TODO uncomment below to declare an instance variable for WebhookAttempts
        //private WebhookAttempts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookAttempts
            //instance = new WebhookAttempts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookAttempts
        /// </summary>
        [Test]
        public void WebhookAttemptsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookAttempts
            //Assert.IsInstanceOfType<WebhookAttempts> (instance, "variable 'instance' is a WebhookAttempts");
        }


        /// <summary>
        /// Test the property 'ClientError'
        /// </summary>
        [Test]
        public void ClientErrorTest()
        {
            // TODO unit test for the property 'ClientError'
        }
        /// <summary>
        /// Test the property 'HookId'
        /// </summary>
        [Test]
        public void HookIdTest()
        {
            // TODO unit test for the property 'HookId'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'ResponseBody'
        /// </summary>
        [Test]
        public void ResponseBodyTest()
        {
            // TODO unit test for the property 'ResponseBody'
        }
        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Test]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'RetriesLeft'
        /// </summary>
        [Test]
        public void RetriesLeftTest()
        {
            // TODO unit test for the property 'RetriesLeft'
        }

    }

}
