/* 
 * Crossbar
 *
 * The Crossbar APIs
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WhitelabelPort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WhitelabelPortTests
    {
        // TODO uncomment below to declare an instance variable for WhitelabelPort
        //private WhitelabelPort instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WhitelabelPort
            //instance = new WhitelabelPort();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhitelabelPort
        /// </summary>
        [Test]
        public void WhitelabelPortInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WhitelabelPort
            //Assert.IsInstanceOfType<WhitelabelPort> (instance, "variable 'instance' is a WhitelabelPort");
        }


        /// <summary>
        /// Test the property 'Authority'
        /// </summary>
        [Test]
        public void AuthorityTest()
        {
            // TODO unit test for the property 'Authority'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'Loa'
        /// </summary>
        [Test]
        public void LoaTest()
        {
            // TODO unit test for the property 'Loa'
        }
        /// <summary>
        /// Test the property 'Resporg'
        /// </summary>
        [Test]
        public void ResporgTest()
        {
            // TODO unit test for the property 'Resporg'
        }
        /// <summary>
        /// Test the property 'SupportEmail'
        /// </summary>
        [Test]
        public void SupportEmailTest()
        {
            // TODO unit test for the property 'SupportEmail'
        }
        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Test]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }

    }

}
